sudo: false

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  # Use Docker rabbitmq instead of Travis'. Travis's gave us test failures
  # with our ChannelFull features, possibly because of feature differences.
  - docker pull rabbitmq:3.7.8-alpine
  - docker run --rm -d -p 5672:5672 rabbitmq:3.7.8-alpine
  # Now it'll start up while we're doing our install. There's a race, but
  # it's extremely likely rabbitmq will be up before pytest starts.

install:
  - pip install black pyflakes isort
  - pip install -e .[tests]
  - pip freeze

script:
  - pyflakes .
  - black --check .
  - isort --check-only --diff --recursive channels_rabbitmq tests
  - pytest --verbose --log-cli-level=debug

deploy:
  provider: pypi
  user: adamhooper
  password:
    secure: "suKZQmAkmtdPIWJkfjI7oU6BoL7qawmGOe21dVwBlgJlLQ/hovsorhy8Ins5rkxnui7k4dRO9djar6XRCPAu2C4045SsKRZXvbjjpD3GUJCuDrLYAFBZ91GFsWX7JhBFumP068KE0XnFYFw5sGCnGYrWwnhnrNSP8ZNnBwQ7Pgb3RK7UPZISuZt2JNudMp7dByigC/yv4B7GnAS7WFh3wPXvAtIrufePrVm0I2rrX+ItXi3+a/un3qccLy+cUNqsH0emrCCHveRHdiCdzG1q3c69h6igjA1rBg1TJlDYtmDUjEZBS02yhX1Q71K+UkoV83IX7GrKa4k/lBXkCciMaFn/MpRrWVgIQNgC/3OGyi3w28IOGQJFUhxGhTyoyxqXKWf6xTyS8QGAZR/YkWMLZI26FBUbpaop8zz8Faxbma289vnWPN33oDnBLCEmzK2l41ChuMz7QpVByX+m/85WmXqmc9V5RM8WaY+oa+ZhCvm2pLHswrRk2CDOWinSfjyaraOTKgvcyLxDwu6Lx7xA9mHAybidfjWP6ZJ6giIE2bos67qVZHSIm5j82u3ksDLfkZJzRtuBfNFyZkuMcO+q1a5WSaRIfTWwnh8XitGBu+z43I1RYW6UZBJRxnML0XULZ8FpvsxFXuRgq+aOxSOMkZk/R4OtIvCMzMg6u+ehxEk="
  on:
    tags: true
