os: linux
dist: focal
language: python

python:
  - "3.8"
  - "3.9"

services:
  - docker
before_install:
  - ssl/prepare-certs.sh
  # Use Docker rabbitmq instead of Travis'. Travis's gave us test failures
  # with our ChannelFull features, possibly because of feature differences.
  - docker pull rabbitmq:3.8.11-alpine
  - docker run --rm -d -p 5671:5671 -p 5672:5672 -v "/${TRAVIS_BUILD_DIR}"/ssl:/ssl -e RABBITMQ_SSL_CACERTFILE=/ssl/ca.cert -e RABBITMQ_SSL_CERTFILE=/ssl/server.cert -e RABBITMQ_SSL_KEYFILE=/ssl/server.key -e RABBITMQ_SSL_VERIFY=verify_peer -e RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=true rabbitmq:3.8.11-alpine
  # Now it'll start up while we're doing our install. There's a race, but
  # it's extremely likely rabbitmq will be up before pytest starts.
  - python -m pip install poetry tox-travis
install: poetry install -v
script: tox

jobs:
  include:
    - stage: deploy
      python: "3.9"
      before_install: python -m pip install poetry
      install: skip
      script: skip
      before_deploy:
        - poetry version $(git describe --tags --exact-match --match="v*.*.*" | cut -b2-)  # fallback "" means, "0.0.0"
        - poetry config pypi-token.pypi $PYPI_TOKEN
      deploy:
        skip_cleanup: true  # so "poetry version" stays
        provider: script
        script: poetry publish --build
        on:
          tags: true

env:
  global:
    - secure: "VIFkyoPhDkYAc8pNvOavctV+vLkLlq1FzmmD1ZGgEC8HVgQUFjIf3WTzOb+Q6QWWIGIcR8xFeBhyOoFbkpleSImvS1DxBBtWyAo6mDKL3OUeUTKOJWFXYtO8W0DWDf+jzG8npBL47Lp4Ye2wgsQ04BZPZAHw+zHZafEK/xkYCChACAzCZn7m4FuRZ12SQ9M+jaXKJb7GkYh7AxFPWk8GNlcvBngGP4WnuZLLcra/XFSsZ5OIPg7SgfaqMWM8R7y3qjKKmNUXwGwn/vMhFSeRgOHkHfghG0Fk2jJ1noY9CoMZFMlHu4x3wplzKHVd777GsFM67T4ydcKqyqpVUj16QbdHtIoWZIJII2ExyF3zm539RlaXBOXHhCs1XlHq4lb4voe7Ya95+Jq5BHLhq+1O000X+w5uMVXUHSgjXIzibYzNMh6YhYNM4F+igCsFvnmJpZkl18nOSZfcsR25sfzHtBGC956vqJYEeHW36ggzjRhMloU1kei7fNipeyA1rWlt+ftO782i+iZu7PlcnLlyguU9BoNbTKDDeEa+WJp2aQwYbRDEiipu33VvLtSGHyJN6I/Pj6FlFbgllwze6vmLlnIq4NbnTxaRVRQk6NSfbl4doSonTV+Uzojc0Nqn5+kU4BC9rWtTAlu1dACU3eSBFZryL2rOm4QqwXuOCBC53V8=" # PYPI_TOKEN=...
